# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: "daily"
    groups:
      pip:
        patterns:
          - "clang-tools"
          - "cpp-linter"

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: "quarterly"
    labels:
      - "dependencies"
      - "python:uv"
      - "skip-changelog"
    groups:
      dev:
        patterns:
          - "mypy"
          - "pre-commit"
          - "ruff"
      docs:
        patterns:
          - "mkdocs-gen-files"
          - "markdown-gfm-admonition"
          - "mkdocs-include-markdown-plugin"
          - "mkdocs-material"
          - "mkdocs"
          - "pyyaml"
