repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: requirements-txt-fixer
  - repo: https://github.com/python/black
    rev: '22.6.0'
    hooks:
      - id: black
        args: ["--diff"]
  - repo: https://github.com/pycqa/pylint
    rev: v2.14.5
    hooks:
      - id: pylint
        name: pylint (action code)
        types: [python]
        exclude: "^(docs/|tests/|setup.py$)"
        additional_dependencies: [pyyaml, requests]
  - repo: local
    # this is a "local" hook to run mypy (see https://pre-commit.com/#repository-local-hooks)
    # because the mypy project doesn't seem to be compatible with pre-commit hooks
    hooks:
      - id: mypy
        name: mypy
        description: type checking with mypy tool
        language: python
        types: [python]
        entry: mypy
        exclude: "^(docs/|setup.py$)"
        additional_dependencies: [mypy, types-pyyaml, types-requests, rich, requests, pytest, pyyaml, '.']
