repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
        # special mkdocs config to include inline icons fails (see `pymdownx.emoji` in mkdocs.yml)
        args: ['--unsafe'] # use `--unsafe` to workaround yaml loading
      - id: requirements-txt-fixer
