name: C/C++ code linter (clang-tidy and clang-format)
description: Automatically checks pull requests changes with clang-tidy, clang-format and posts the comment with result.
author: shenxianpeng
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  style: # the specific style rules
    description: "The style rules to use (defaults to 'llvm'). Set this to 'file' to have clang-format use the closest relative .clang-format file."
    required: false
    default: 'llvm'
  extensions:
    description: "The file extensions to run the action against. This comma-separated string defaults to 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'."
    required: false
    default: "c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx"
outputs:
  checks-failed:
    description: An integer that can be used as a boolean value to indicate if all checks failed.
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.style }}
    - ${{ inputs.extensions }}
