[project]
name = "cpp-linter-action"
version = "0.0.0+private_virtual"
requires-python = ">=3.9"
dependencies = []

[dependency-groups]
action = [
    "clang-tools==0.15.2",
    "cpp-linter==2.0.0rc12",
]
dev = [
    "mypy>=1.17.1",
    "pre-commit>=4.3.0",
    "ruff>=0.12.8",
]
docs = [
    "markdown-gfm-admonition>=0.1.1",
    "mkdocs>=1.6.1",
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-include-markdown-plugin>=7.1.6",
    "mkdocs-material>=9.6.16",
    "pyyaml>=6.0.2",
]

[[tool.uv.index]]
name = "testPyPI"
url = "https://test.pypi.org/simple/"
explicit = true

[tool.uv.sources]
cpp-linter = { index = "testPyPI" }
