---
name: Feature request
description: Suggest an idea for this project
body:
  - type: dropdown
    id: existing-feature
    attributes:
      label: Is your idea related to an existing feature?
      description: >-
        If this idea is related to an already available feature(s), then please list them here.
      multiple: true
      options:
        - version
        - database
        - thread-comments
        - tidy-checks
        - style
        - lines-changed-only
        - ignore
        - tidy-ignore
        - format-ignore
        - files-changed-only
        - file-annotations
        - step-summary
        - no-lgtm
        - tidy-review
        - format-review
        - passive-reviews
        - verbosity
        - 'output: checks-failed'
        - 'output: clang-tidy-checks-failed'
        - 'output: clang-format-checks-failed'

  - type: textarea
    id: behavior
    attributes:
      label: Describe the behavior you would like
      description: >-
        Use this area to describe what behavior you desire.
        Please be clear and concise as possible. Use screenshots if that would help.
      placeholder: You can use markdown syntax here
    validations:
      required: true

  - type: textarea
    id: alternative
    attributes:
      label: Describe alternatives you have considered
      description: >-
        Were you able to achieve the desired behavior in some other/inconvenient way?
      placeholder: You can use markdown syntax here

  - type: textarea
    id: added-context
    attributes:
      label: Additional context
      description: >-
        If there is anything that might be special or specific to your usage, please let us know.
      placeholder: You can use markdown syntax here
