name: PR Auto-labeler

on:
  # pull_request event is required for auto-labeler
  pull_request:
    types: [opened, reopened, synchronize]

permissions: {}

jobs:
  draft-release:
    permissions:
      contents: read
      pull-requests: write
    uses: cpp-linter/.github/.github/workflows/pr-labeler.yml@main
