name: Release Drafter

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  update_release_draft:
    uses: cpp-linter/.github/.github/workflows/release-drafter.yml@reusable-workflows
