name: "Check python code"

on:
  push:
    paths:
      - "**.py"
      - .pylintrc
      - mypy.ini
      - ".github/workflows/run-dev-tests.yml"
  pull_request:
    types: opened
    paths:
      - "**.py"
      - .pylintrc
      - mypy.ini
      - ".github/workflows/run-dev-tests.yml"

jobs:
  check-python-sources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: python3 -m pip install pre-commit
      - run: pre-commit run --all-files

  run-pytest:
    strategy:
      fail-fast: false
      matrix:
        py: ['3.7', '3.8', '3.9', '3.10']
        os: ['windows-latest', ubuntu-latest]
        version: ['14', '13', '12', '11', '10']
        include:
          - tools_dir: 'N/A'
          - os: 'windows-latest'
            version: '10'
            tools_dir: temp
          - os: 'windows-latest'
            version: '10'
            tools_dir: temp
          - os: 'windows-latest'
            version: '11'
            tools_dir: temp
          - os: 'windows-latest'
            version: '12'
            tools_dir: temp
          - os: 'ubuntu-latest'
            version: '13'
            tools_dir: temp
          - version: '14'
            tools_dir: temp

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}

      - name: Install workflow deps
        run: python3 -m pip install pytest coverage .

      # - name: Install clang-tools
      #   if: matrix.tools_dir == 'temp'
      #   run: |
      #     python -m pip install clang-tools
      #     clang-tools --install ${{ matrix.version }} --directory ${{ runner.temp }}/llvm
      
      - name: Install clang-tools
        uses: KyleMayes/install-llvm-action@v1
        if: matrix.tools_dir == 'temp'
        with:
          version: ${{ matrix.version }}
          directory: ${{ runner.temp }}/llvm

      - name: Collect Coverage (native clang)
        if: matrix.tools_dir == 'N/A' || matrix.os == 'ubuntu-latest'
        env:
          CLANG_VERSION: ${{ matrix.version }}
        run: coverage run -m pytest -vv tests

      - name: Collect Coverage (non-native clang windows)
        if: matrix.tools_dir == 'temp' && matrix.os == 'windows-latest'
        env:
          CLANG_VERSION: ${{ runner.temp }}/llvm
        run: coverage run -m pytest -vv tests

      - run: coverage report && coverage xml

      - uses: codecov/codecov-action@v3
        env:
          OS: ${{ matrix.os }}
          PYTHON: CPy${{ matrix.py }}
          CLANG: LLVM-v${{ matrix.version }}
        with:
          # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage.xml
          env_vars: OS,PYTHON,CLANG # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)