name: Pre-commit

on:
  push:
  pull_request:
    types: opened

jobs:
  check-source-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: python3 -m pip install pre-commit
      - run: pre-commit run --all-files
