name: "Check python code"

on:
  push:
    paths:
      - "**.py"
      - .pylintrc
      - mypy.ini
      - ".github/workflows/run-pylint.yml"
  pull_request:
    types: opened
    paths:
      - "**.py"
      - .pylintrc
      - mypy.ini
      - ".github/workflows/run-pylint.yml"

jobs:
  check-python-sources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install workflow deps
        run: python3 -m pip install -r requirements.txt -r requirements-dev.txt .
      - name: run pylint
        run: |
          pylint cpp_linter/**
          pylint setup.py
      - run: mypy cpp_linter/
      - run: pytest -vv tests
