name: 'Close stale issues'
on:
  schedule:
    - cron: '30 1 * * *'
permissions: {}

jobs:
  stale:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: cpp-linter/.github/.github/workflows/stale.yml@main
